#!/bin/sh

npm run build

# scp -i ~/.ssh/id_rsa -r -P 22 .nuxt andrey@92.63.192.228:/srv/santex/site
# scp -i ~/.ssh/id_rsa -r -P 22 static andrey@92.63.192.228:/srv/santex/site_mobile
tar -czvf build.tar.gz -C .nuxt .
ssh -p 22 andrey@92.63.192.228 rm -r /srv/santex/site_mobile/.nuxt
scp -r -P 22 build.tar.gz andrey@92.63.192.228:/srv/santex/site_mobile/
ssh -p 22 andrey@92.63.192.228 mkdir /srv/santex/site_mobile/.nuxt
ssh -p 22 andrey@92.63.192.228 tar -xvzf /srv/santex/site_mobile/build.tar.gz -C /srv/santex/site_mobile/.nuxt

scp -i ~/.ssh/id_rsa -r -P 22 nuxt.config.js andrey@92.63.192.228:/srv/santex/site_mobile
scp -i ~/.ssh/id_rsa -r -P 22 package.json andrey@92.63.192.228:/srv/santex/site_mobile

ssh andrey@92.63.192.228 pm2 restart 7

git add .
git commit -m 'commit'
# git push origin master
git push